### ISSUE TITLE
Hello！How can  I get the file "/hy-tmp/molecule_net/summary.json"?

### ISSUE THREAD

**Issue by chushuang203** [A-Gentle-Cat/PremuNet#1]

**Comment by A-Gentle-Cat** [comment]
Thank you for your interest in our project! We apologize for the unclear documentation. For `summary.json`, it should be obtained from [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JNGTDF), download `molecule_net.tar.gz` and unzip to the `/dataset` directory. The relevant instructions have also been added to the README.

If you have any questions, feel free to contact me further.
