### ISSUE TITLE
How to  Pretrain on Graph-Level? 

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [A-Gentle-Cat/PremuNet#2]
The link in Graph-Level Pretrain is smiles-transformer,is  same as atomic-level pretrain.

**Comment by A-Gentle-Cat** [comment]
Thanks for your interest in our paper. The modules for both graph-level and atomic-level are based on the SMILES-Transformer architecture, and their essential difference lies in the identification of tokens in SMILES strings and the way features are used. For the graph-level module, the pre-training method can directly refer to the steps given in the SMILES-Transformer project.

**Comment by hzlhzlhzlhzl** [comment]
> 感谢您对我们的论文感兴趣。图级和原子级模块均基于SMILES-Transformer架构，其本质区别在于SMILES字符串中token的识别以及特征的使用方式。对于图级模块，预训练方法可以直接参考SMILES-Transformer项目中给出的步骤。

那我应该使用SMILES-Transformer的代码进行图级别预训练吗？

**Comment by A-Gentle-Cat** [comment]
> > 感谢您对我们的论文感兴趣。图级和原子级模块均基于SMILES-Transformer架构，其本质区别在于SMILES字符串中token的识别以及特征的使用方式。对于图级模块，预训练方法可以直接参考SMILES-Transformer项目中给出的步骤。
> 
> 那我应该使用SMILES-Transformer的代码进行图级别预训练吗？

是的
