### ISSUE TITLE
pre-training PremuNet-H

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [A-Gentle-Cat/PremuNet#3]
在处理pcqm4m数据时候
![微信图片_20231220165428](https://github.com/A-Gentle-Cat/PremuNet/assets/94671385/2f84f0e8-9b36-45af-b6b6-7b6f01fd05d4)
为什么只取100个分子？

在预训练的时候输入与模型不匹配RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x9 and 173x1024)

**Comment by hzlhzlhzlhzl** [comment]
而且batch中没有smiles_list,但是网络中确有这个，导致预训练代码运行失败，请问这是什么问题呢？

**Comment by A-Gentle-Cat** [comment]
抱歉，PremuNet-H 部分的代码包含了一些手稿的内容，现在已经重新推送了 UnifiedMolPretrain 部分的代码，经过我们测试可以正常预训练，我们使用的启动指令如下：

```bash
cd UnifiedMolPretrain
python train.py --num-layers 12 --batch-size 128 --enable-tb --node-attn --use-bn --pred-pos-residual --mask-prob 0.25
```

另外，建议在预训练 PremuNet-H 时代码使用单独的项目空间或修改Python工作空间为`/UnifiedMolPretrain`，以避免可能的相对路径错误。
