### ISSUE TITLE
ModuleNotFoundError: No module named 'TransformerData'

### ISSUE THREAD

**Issue by oosuw063** [A-Gentle-Cat/PremuNet#4]
Thank you very much for your great work.But I meet a error 'ModuleNotFoundError: No module named 'TransformerData'' when i run python pretrain_trfm.py in Transformer1D.

**Comment by A-Gentle-Cat** [comment]
We apologize for the error due to a redundant introduction, we have fixed the bug and updated the readme, please pull the code again.
