### ISSUE TITLE
Finetune of SMILES Tranformer

### ISSUE THREAD

**Issue by chushuang203** [A-Gentle-Cat/PremuNet#5]
你好，我想请问下：
首先，在PCQM4Mv2数据集上预训练SMILES Tranformer；
然后，用预训练的SMILES Tranformer去提取BBBP数据集中分子的原子特征作为GNN模型初始特征，
最后，合并原子特征生产分子表示做预测。
这个过程中预训练的SMILES Tranformer是否需要微调呢，请问是如何微调的？谢谢。

**Comment by A-Gentle-Cat** [comment]
不需要，SMILES-transfrmer预训练完成后仅作为特征提取模块使用，不参与训练

**Comment by chushuang203** [comment]
> 不需要，SMILES-transfrmer预训练完成后仅作为特征提取模块使用，不参与训练

好的谢谢
