### ISSUE TITLE
External validation of SMILES-Transformer

### ISSUE THREAD

**Issue by chushuang203** [A-Gentle-Cat/PremuNet#6]
作者您好，非常感谢您之前的及时回复；我最近在研究BBB预测问题，因此对于SMILES-Transformer我想向您请教一个问题：
       1）当用SMILES-Transformer提取原子特征作为原子初始特征，利用GNN在BBBP数据集上做二分类时效果较好；
       2）但是在外部验证（独立测试），或者其他血脑屏障通透性数据集上效果较差；
请问这有可能是什么原因导致的呢，谢谢？

**Comment by A-Gentle-Cat** [comment]
你好，如果没有在新的数据集上微调，模型的其他特征提取部分（2D、3D）的参数可能都不能与新数据集涉及到的分子结构相匹配，所以难以提取到有效的特征。如果只针对 SMILES-Transformer，可能是预训练数据集与新数据集的分子类型差异较大，从而导致特征提取性能较差。

**Comment by chushuang203** [comment]
> 你好，如果没有在新的数据集上微调，模型的其他特征提取部分（2D、3D）的参数可能都不能与新数据集涉及到的分子结构相匹配，所以难以提取到有效的特征。如果只针对 SMILES-Transformer，可能是预训练数据集与新数据集的分子类型差异较大，从而导致特征提取性能较差。

谢谢，这里我是只针对SMILES-Transformer；
1）我尝试加载您提供的预训练模型(参数)，并再在新的数据集上（3343个分子）微调参数(此时依然是掩盖然后恢复序列，并没有加入下游任务），但是结果好像依然不是很理想；
2）我在想是不是新的数据集数量太少的原因，所以我在尝试加入更多的新数据集来预训练模型；
再次感谢您的指导！

**Comment by A-Gentle-Cat** [comment]
不客气，我猜测原因可能这么几个方面：
1. 可能是因为数据量较少（相对于原预训练数据集1M的量），对权重影响不大，可以尝试调参或者从零训练，或者加入更多类似数据；
2. 可能是该数据集的任务对SMILES 特征不敏感，即SMILES 串隐含的特征与任务关联度不高，可以尝试从其他维度提取特征；
3. 也有可能是任务本身难度就较大，SMILES-Transformer 提取能力有限，需要更有效的模型结构。

**Comment by chushuang203** [comment]
> 不客气，我猜测原因可能这么几个方面：
> 
> 1. 可能是因为数据量较少（相对于原预训练数据集1M的量），对权重影响不大，可以尝试调参或者从零训练，或者加入更多类似数据；
> 2. 可能是该数据集的任务对SMILES 特征不敏感，即SMILES 串隐含的特征与任务关联度不高，可以尝试从其他维度提取特征；
> 3. 也有可能是任务本身难度就较大，SMILES-Transformer 提取能力有限，需要更有效的模型结构。

好的好的，非常谢谢您的指导，我会结合您说的原因再多多思考和实验
