### ISSUE TITLE
Unable to load the pre-trained model.

### ISSUE THREAD

**Issue by Moohyun-w** [A-Gentle-Cat/PremuNet#7]
您好，我在使用您预训练好的模型（checkpoint_20.pt）做下游任务的微调时，出现了无法正确载入模型的问题。
这个问题出现在UnifiedMolPretrain.pretrain3d.model.gnn.py文件中的class GNNet类下的load_state_dict函数中。在尝试加载预训练模型的状态字典（state_dict）到GNNet模型时遇到了几个错误：
1.Missing key(s) in state_dict: 表示在你尝试加载的state_dict中缺少一些在当前模型定义中应有的参数
2.Unexpected key(s) in state_dict: 这意味着state_dict中包含了一些当前模型定义中没有的额外参数
3.size mismatch for global_init: 这个错误说明了某个参数“global_init”的尺寸不匹配

我想问一下加载模型时会否有额外的注意事项？
或者您是否能重新提供一份当前模型的预训练权重？

万分感谢，期待您的回复！
<img width="691" alt="微信图片_20240601193959" src="https://github.com/A-Gentle-Cat/PremuNet/assets/68847910/8330644e-eebf-4d4d-8d2b-8ab2062bc59a">

**Comment by A-Gentle-Cat** [comment]
很抱歉由于之前的一次错误提交，引起了一些错误，我们已经修复了代码，并推送了新的版本，如果还有问题，欢迎继续与我联系。

**Comment by Moohyun-w** [comment]
> 很抱歉由于之前的一次错误提交，引起了一些错误，我们已经修复了代码，并推送了新的版本，如果还有问题，欢迎继续与我联系。

您好，在PremuNet-main/UnifiedMolPretrain/pretrain3d/model/gnn.py文件中，您似乎调用了上级文件夹中的data.MolFeature和utils.PreProcessor文件，但我在您的PremuNet-main/UnifiedMolPretrain/pretrain3d/目录下并没有找到这两个文件。您是否能够核查一下，并再次上传一遍代码？非常感谢！
<img width="332" alt="图片1" src="https://github.com/A-Gentle-Cat/PremuNet/assets/68847910/9794e94c-76cb-4a9c-a4d4-2a6632b1495b">

**Comment by A-Gentle-Cat** [comment]
好的，刚刚上传了这两个文件，您重新试一下

**Comment by Moohyun-w** [comment]
> 好的，刚刚上传了这两个文件，您重新试一下

不好意思，再次打扰！在/data/wanmx/premunet1/PremuNet-main/LoadData/qm9_loader.py文件中，您调用了FeatureDefine.AtomFeature和FeatureDefine.BondFeature，但我在您的/data/wanmx/premunet1/PremuNet-main/FeatureDefine/目录下并没有找到AtomFeature.py和BondFeature.py这两个文件。您是否能够核查一下，并再次上传一遍代码？非常感谢！

**Comment by Moohyun-w** [comment]
此外，对于QM9，QM8，TOXCAST这种包含了多处空值的多任务数据集，是否能够直接使用您提供的pretrans_data.py文件进行数据预处理呢？如果不能，我想知道您有什么建议呢？

**Comment by A-Gentle-Cat** [comment]
我们代码评估中没有包含qm9、qm8和TOXCAST，`qm9_loader.py`和`qm8_loader.py`是遗弃的文件，其他代码中并没有使用到该文件。如果您想要在qm9等其他数据集上评估，应该可以直接使用`pretrans_data.py`产生特征，因为它只使用了SMILES串。对于label的缺失值，训练中做了忽略处理，您可以尝试一下。
